
import { ChartColumn, LayoutDashboard, ListTodo, Zap, GitBranchPlus } from 'lucide-react';
import { Category } from './types';

export const APP_NAME = "ChronoFlow";

export const TRANSLATIONS = {
  en: {
    aiSettings: "AI Config",
    provider: "Provider",
    apiKey: "API Key",
    modelName: "Model",
    endpoint: "Endpoint",
    saveConfig: "Save",
    configSaved: "Updated",
    useDefault: "Default",
    geminiDesc: "Google Gemini",
    deepseekDesc: "DeepSeek / SiliconFlow",
    tasks: "Flow",
    projects: "Projects",
    analytics: "Statistics",
    aiInsights: "AI Coach",
    darkMode: "Dark",
    lightMode: "Light",
    export: "Backup",
    import: "Restore",
    langName: "简体中文",
    noActiveTask: "What's the goal?",
    selectTaskToStart: "Start a task to enter deep work mode.",
    taskCreated: "Task started",
    newMilestone: "What's the update?",
    add: "Add",
    cancel: "Cancel",
    taskExplorer: "Task List",
    standaloneTasks: "Quick Tasks",
    all: "All",
    active: "Working",
    done: "Done",
    quickAdd: "I want to...",
    noTasksYet: "Peaceful Mind",
    createTaskHint: "Add a task above to start your journey.",
    projectPlanner: "Projects",
    projectPlannerDesc: "Group tasks into structured goals.",
    newProject: "New Project",
    createProject: "Create Project",
    projectName: "Name",
    description: "Brief",
    themeColor: "Color",
    workflowSteps: "Steps",
    addStep: "Add Step",
    stepName: "Step title...",
    noDependency: "No parent",
    dependsOn: "Needs:",
    workflowTip: "Tasks unlock as you complete prerequisites.",
    totalTime: "Total Focused",
    tasksCompleted: "Goals",
    avgTaskTime: "Pace",
    mostActiveTag: "Top Category",
    timeByTag: "Duration / Tag",
    taskDistribution: "Focus Mix",
    weeklyDist: "Weekly Distribution",
    totalDist: "Total Distribution",
    aiCoach: "AI Coach",
    aiCoachDesc: "Let AI analyze your data and give advice.",
    analyzeWorkflow: "Start Audit",
    completeTasksFirst: "Track more data first!",
    thinking: "AI is thinking...",
    report: "Focus Audit",
    summary: "Overview",
    improvements: "Advice",
    regenerate: "Retry",
    waitingForParent: "Locked",
    stepsCompleted: "completed",
    deleteProjectWarning: "Delete project structure?",
    dataTransparency: "Data Privacy",
    dataSentToAI: "Sent to AI",
    dataExplanation: "Only anonymous titles and durations are sent.",
    apiKeyRequired: "API Key detected.",
    listView: "List",
    graphView: "Map",
    taskLimitReached: "Only one active timer allowed.",
    manageCategories: "Tags",
    categoryName: "Name",
    newCategory: "New Tag",
    selectColor: "Color",
    deleteCategoryConfirm: "Delete this tag?",
    suggestedTasks: "Suggestions",
    onBreak: "Rest Time",
    startBreak: "Start Break",
    endBreak: "Resume Work",
    pomodoroTip: "Great work! Time for a 5-min break?",
    sessionProgress: "Current Session"
  },
  zh: {
    aiSettings: "AI 配置",
    provider: "服务商",
    apiKey: "密钥",
    modelName: "模型",
    endpoint: "端点",
    saveConfig: "保存",
    configSaved: "已更新",
    useDefault: "默认",
    geminiDesc: "Google Gemini",
    deepseekDesc: "DeepSeek / 硅基流动",
    tasks: "专注",
    projects: "项目",
    analytics: "统计",
    aiInsights: "教练",
    darkMode: "深色",
    lightMode: "浅色",
    export: "备份",
    import: "还原",
    langName: "English",
    noActiveTask: "当前目标是什么？",
    selectTaskToStart: "开始一个任务，进入深度工作状态。",
    taskCreated: "任务已开始",
    newMilestone: "有什么新进展？",
    add: "添加",
    cancel: "取消",
    taskExplorer: "任务清单",
    standaloneTasks: "快速任务",
    all: "全部",
    active: "进行中",
    done: "已完成",
    quickAdd: "我准备...",
    noTasksYet: "享受当下",
    createTaskHint: "在上方添加一个任务开始计时吧。",
    projectPlanner: "项目管理",
    projectPlannerDesc: "将任务组织成结构化的目标。",
    newProject: "新建项目",
    createProject: "创建项目",
    projectName: "项目名",
    description: "描述",
    themeColor: "主题色",
    workflowSteps: "步骤",
    addStep: "添加步骤",
    stepName: "步骤标题...",
    noDependency: "无前置",
    dependsOn: "前置:",
    workflowTip: "任务将随着前置条件的达成自动解锁。",
    totalTime: "总专注时长",
    tasksCompleted: "达成目标",
    avgTaskTime: "平均节奏",
    mostActiveTag: "主要领域",
    timeByTag: "耗时分布",
    taskDistribution: "专注偏好",
    weeklyDist: "最近一周耗时分布",
    totalDist: "总耗时分布",
    aiCoach: "AI 教练",
    aiCoachDesc: "让 AI 分析您的数据并提供建议。",
    analyzeWorkflow: "开始审计",
    completeTasksFirst: "请记录更多数据！",
    thinking: "AI 正在思考...",
    report: "专注审计报告",
    summary: "执行摘要",
    improvements: "行动建议",
    regenerate: "重新生成",
    waitingForParent: "锁定中",
    stepsCompleted: "个步骤已完成",
    deleteProjectWarning: "确定要删除项目结构吗？",
    dataTransparency: "隐私说明",
    dataSentToAI: "发送的数据",
    dataExplanation: "我们仅发送匿名的标题和时长，日志保存在本地。",
    apiKeyRequired: "已检测到 API Key。",
    listView: "列表",
    graphView: "地图",
    taskLimitReached: "仅允许同时开启一个计时任务。",
    manageCategories: "标签管理",
    categoryName: "标签名",
    newCategory: "新标签",
    selectColor: "颜色",
    deleteCategoryConfirm: "确定删除标签吗？",
    suggestedTasks: "推荐任务",
    onBreak: "休息一下",
    startBreak: "开始休息",
    endBreak: "继续工作",
    pomodoroTip: "太棒了！休息 5 分钟补充一下精力？",
    sessionProgress: "当前环节"
  }
};

export const NAV_ITEMS = [
  { id: 'tasks', labelKey: 'tasks', icon: ListTodo },
  { id: 'projects', labelKey: 'projects', icon: GitBranchPlus },
  { id: 'dashboard', labelKey: 'analytics', icon: ChartColumn },
  { id: 'ai-insights', labelKey: 'aiInsights', icon: Zap },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'c1', name: 'Study', color: 'indigo' },
  { id: 'c2', name: 'Work', color: 'slate' },
  { id: 'c3', name: 'Exercise', color: 'emerald' },
  { id: 'c4', name: 'Creative', color: 'rose' }
];

export const TAG_COLORS = [
  'indigo', 'emerald', 'slate', 'rose', 'amber', 'cyan', 'violet', 'fuchsia'
];
