
import { ChartColumn, LayoutDashboard, ListTodo, Zap, GitBranchPlus } from 'lucide-react';
import { Category } from './types';

export const APP_NAME = "ChronoFlow";

export const TRANSLATIONS = {
  en: {
    tasks: "Timer Dashboard",
    projects: "Workflow Planner",
    analytics: "Stats & Trends",
    aiInsights: "AI Coach",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    export: "Backup Data",
    import: "Restore Data",
    langName: "简体中文",
    noActiveTask: "Ready for Flow?",
    selectTaskToStart: "Select or create tasks below to start timing. You can run up to 3 timers at once to manage your multitasking.",
    taskCreated: "Task initialized",
    newMilestone: "What happened just now?",
    add: "Add",
    cancel: "Cancel",
    taskExplorer: "Task Repository",
    standaloneTasks: "Quick Tasks",
    all: "All",
    active: "Working",
    done: "Finished",
    quickAdd: "What needs to be done?",
    noTasksYet: "The slate is clean",
    createTaskHint: "Start by adding a standalone task or planning a project workflow.",
    projectPlanner: "Project Architect",
    projectPlannerDesc: "Design complex task structures with smart dependencies and visual graphs.",
    newProject: "New Project",
    createProject: "Blueprint a Project",
    projectName: "Project Identity",
    description: "Brief Overview",
    themeColor: "Aura Color",
    workflowSteps: "Blueprint Steps",
    addStep: "Add Phase",
    stepName: "Phase title...",
    noDependency: "Root phase (No parents)",
    dependsOn: "Requirements:",
    workflowTip: "Smart Locking: Tasks with dependencies stay locked until their prerequisites are fully completed.",
    totalTime: "Chronos Spent",
    tasksCompleted: "Goals Reached",
    avgTaskTime: "Pace (Avg Time)",
    mostActiveTag: "Deepest Category",
    timeByTag: "Minutes by Category",
    taskDistribution: "Focus Distribution",
    aiCoach: "Gemini Productivity Coach",
    aiCoachDesc: "Leverage AI-powered reasoning to audit your time tracking data and receive strategic advice.",
    analyzeWorkflow: "Audit My Workflow",
    completeTasksFirst: "Track more data to unlock insights!",
    geminiThinking: "Gemini is analyzing your focus patterns...",
    report: "Executive Focus Report",
    summary: "Strategic Summary",
    improvements: "Strategic Improvements",
    regenerate: "Refresh Analysis",
    waitingForParent: "Locked: Prerequisite needed",
    stepsCompleted: "milestones reached",
    deleteProjectWarning: "Deleting a project will dissolve its structure, but tasks remain as standalone items. Proceed?",
    dataTransparency: "Privacy & Data",
    dataSentToAI: "Data Sent to AI",
    dataExplanation: "Only anonymized task titles, tags, and total minutes are analyzed. Full logs and timestamps stay private on your device.",
    apiKeyRequired: "Active API key detected in environment.",
    listView: "Flow View",
    graphView: "Map View",
    taskLimitReached: "Focus Limit: You can only have 3 active timers. Please pause a current task to start a new one.",
    manageCategories: "Manage Categories",
    categoryName: "Category Name",
    newCategory: "New Category",
    selectColor: "Select Color",
    deleteCategoryConfirm: "Are you sure? Tasks using this category will remain, but the tag will be removed."
  },
  zh: {
    tasks: "计时控制台",
    projects: "工作流规划",
    analytics: "数据趋势",
    aiInsights: "AI 教练",
    darkMode: "深色模式",
    lightMode: "浅色模式",
    export: "备份数据",
    import: "还原数据",
    langName: "English",
    noActiveTask: "准备进入心流？",
    selectTaskToStart: "从下方列表中选择或创建任务开始计时。您可以同时运行最多3个计时器来管理多项工作。",
    taskCreated: "任务已初始化",
    newMilestone: "刚才发生了什么？",
    add: "添加",
    cancel: "取消",
    taskExplorer: "任务仓库",
    standaloneTasks: "独立任务",
    all: "全部",
    active: "进行中",
    done: "已完成",
    quickAdd: "准备做什么？",
    noTasksYet: "看板非常整洁",
    createTaskHint: "通过添加独立任务或规划项目工作流开始吧。",
    projectPlanner: "项目建筑师",
    projectPlannerDesc: "通过智能依赖和可视化图表设计复杂的工作流结构。",
    newProject: "新建项目",
    createProject: "规划新项目",
    projectName: "项目名称",
    description: "简要概述",
    themeColor: "主题色",
    workflowSteps: "工作流步骤",
    addStep: "添加阶段",
    stepName: "阶段标题...",
    noDependency: "根阶段（无依赖）",
    dependsOn: "前置要求:",
    workflowTip: "智能锁定：具有依赖关系的任务在所有前置要求完成前将保持锁定状态。",
    totalTime: "累计耗时",
    tasksCompleted: "达成目标",
    avgTaskTime: "平均节奏",
    mostActiveTag: "最深耕分类",
    timeByTag: "各分类耗时 (分钟)",
    taskDistribution: "专注度分布",
    aiCoach: "Gemini 生产力教练",
    aiCoachDesc: "利用 AI 推理审计您的时间记录，并接收战略性建议。",
    analyzeWorkflow: "审计我的工作流",
    completeTasksFirst: "请记录更多数据以解锁洞察！",
    geminiThinking: "Gemini 正在分析您的专注模式...",
    report: "执行专注报告",
    summary: "战略摘要",
    improvements: "战略改进建议",
    regenerate: "刷新分析",
    waitingForParent: "已锁定：需先完成前序任务",
    stepsCompleted: "个步骤已达成",
    deleteProjectWarning: "删除项目将解散其结构，但任务将保留为独立项。是否继续？",
    dataTransparency: "隐私与数据",
    dataSentToAI: "发送给 AI 的数据",
    dataExplanation: "我们仅分析匿名的任务标题、标签和总耗时（分钟）。完整日志和时间戳保存在本地。",
    apiKeyRequired: "已检测到环境中的有效 API Key。",
    listView: "列表流",
    graphView: "地图流",
    taskLimitReached: "专注力上限：您最多只能同时进行 3 个计时器。请先暂停一个任务后再开始新任务。",
    manageCategories: "管理分类标签",
    categoryName: "分类名称",
    newCategory: "新增分类",
    selectColor: "选择颜色",
    deleteCategoryConfirm: "确定要删除此分类吗？使用该分类的任务不会被删除，但标签会移除。"
  }
};

export const NAV_ITEMS = [
  { id: 'tasks', labelKey: 'tasks', icon: ListTodo },
  { id: 'projects', labelKey: 'projects', icon: GitBranchPlus },
  { id: 'dashboard', labelKey: 'analytics', icon: ChartColumn },
  { id: 'ai-insights', labelKey: 'aiInsights', icon: Zap },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'c1', name: 'Study', color: 'indigo' },
  { id: 'c2', name: 'Exercise', color: 'emerald' },
  { id: 'c3', name: 'Work', color: 'slate' },
  { id: 'c4', name: 'Creative', color: 'rose' }
];

export const TAG_COLORS = [
  'indigo', 'emerald', 'slate', 'rose', 'amber', 'cyan', 'violet', 'fuchsia'
];
