import { ChartColumn, LayoutDashboard, ListTodo, Zap, GitBranchPlus } from 'lucide-react';
import { Category } from './types';

export const APP_NAME = "ChronoFlow";

export const TRANSLATIONS = {
  en: {
    tasks: "Tasks",
    projects: "Projects",
    analytics: "Analytics",
    aiInsights: "AI Insights",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    export: "Export",
    import: "Import",
    langName: "简体中文",
    noActiveTask: "No active task",
    selectTaskToStart: "Select a task from the list to start timing.",
    taskCreated: "Task Created",
    newMilestone: "New milestone...",
    add: "Add",
    cancel: "Cancel",
    taskExplorer: "Task Explorer",
    standaloneTasks: "Standalone Tasks",
    all: "All",
    active: "Active",
    done: "Done",
    quickAdd: "Quick add standalone task...",
    noTasksYet: "No tasks yet",
    createTaskHint: "Create a standalone task or start a project.",
    projectPlanner: "Project Planner",
    projectPlannerDesc: "Define complex workflows with step-by-step dependencies.",
    newProject: "New Project",
    createProject: "Create New Project",
    projectName: "Project Name",
    description: "Description",
    themeColor: "Theme Color",
    workflowSteps: "Workflow Steps",
    addStep: "Add Project Step",
    stepName: "Step name...",
    noDependency: "No dependency (Starts project)",
    dependsOn: "Depends on:",
    workflowTip: "Workflow Tip: Tasks with dependencies (Parent Tasks) will remain locked in your task list until the parent step is marked as Completed.",
    totalTime: "Total Time",
    tasksCompleted: "Tasks Completed",
    avgTaskTime: "Avg Task Time",
    mostActiveTag: "Most Active Tag",
    timeByTag: "Time by Tag (Minutes)",
    taskDistribution: "Task Distribution",
    aiCoach: "AI Productivity Coach",
    aiCoachDesc: "Use Google Gemini to analyze your time tracking logs and get personalized advice.",
    analyzeWorkflow: "Analyze My Workflow",
    completeTasksFirst: "Complete some tasks first!",
    geminiThinking: "Gemini is thinking...",
    report: "Productivity Report",
    summary: "Executive Summary",
    improvements: "Key Improvements",
    regenerate: "Regenerate Analysis",
    waitingForParent: "Waiting for previous step...",
    stepsCompleted: "steps completed",
    deleteProjectWarning: "Deleting a project will make its tasks standalone. Continue?",
    dataTransparency: "Data Transparency",
    dataSentToAI: "What data is sent to AI?",
    dataExplanation: "We only send task titles, tags, and durations. No personal information or full logs are uploaded.",
    apiKeyRequired: "API Key required in environment (process.env.API_KEY)"
  },
  zh: {
    tasks: "任务",
    projects: "项目规划",
    analytics: "数据统计",
    aiInsights: "AI 洞察",
    darkMode: "深色模式",
    lightMode: "浅色模式",
    export: "导出数据",
    import: "导入数据",
    langName: "English",
    noActiveTask: "暂无活动任务",
    selectTaskToStart: "从列表中选择一个任务开始计时。",
    taskCreated: "任务已创建",
    newMilestone: "新里程碑...",
    add: "添加",
    cancel: "取消",
    taskExplorer: "任务浏览器",
    standaloneTasks: "单独任务一览",
    all: "全部",
    active: "进行中",
    done: "已完成",
    quickAdd: "快速添加独立任务...",
    noTasksYet: "尚无任务",
    createTaskHint: "创建一个独立任务或启动一个项目。",
    projectPlanner: "项目规划器",
    projectPlannerDesc: "通过步骤依赖定义复杂的工作流。",
    newProject: "新建项目",
    createProject: "创建新项目",
    projectName: "项目名称",
    description: "描述信息",
    themeColor: "主题颜色",
    workflowSteps: "工作流步骤",
    addStep: "添加项目步骤",
    stepName: "步骤名称...",
    noDependency: "无依赖（作为起点）",
    dependsOn: "依赖于:",
    workflowTip: "工作流提示：具有依赖关系的任务（父任务）在父步骤标记为“已完成”之前，将在任务列表中保持锁定状态。",
    totalTime: "累计时间",
    tasksCompleted: "已完成任务",
    avgTaskTime: "平均用时",
    mostActiveTag: "最活跃标签",
    timeByTag: "各标签耗时 (分钟)",
    taskDistribution: "任务分布",
    aiCoach: "AI 生产力教练",
    aiCoachDesc: "使用 Google Gemini 分析您的时间追踪日志，获取个性化建议。",
    analyzeWorkflow: "开始分析我的工作流",
    completeTasksFirst: "请先完成一些任务！",
    geminiThinking: "Gemini 正在思考...",
    report: "生产力分析报告",
    summary: "执行摘要",
    improvements: "关键改进建议",
    regenerate: "重新生成分析",
    waitingForParent: "等待前序步骤完成...",
    stepsCompleted: "个步骤已完成",
    deleteProjectWarning: "删除项目将使其下属任务变为独立任务。是否继续？",
    dataTransparency: "数据透明度",
    dataSentToAI: "哪些数据会被发送给 AI？",
    dataExplanation: "我们仅发送任务标题、标签和耗时。不上传个人隐私或完整日志。",
    apiKeyRequired: "需要环境中的 API Key (process.env.API_KEY)"
  }
};

export const NAV_ITEMS = [
  { id: 'tasks', labelKey: 'tasks', icon: ListTodo },
  { id: 'projects', labelKey: 'projects', icon: GitBranchPlus },
  { id: 'dashboard', labelKey: 'analytics', icon: ChartColumn },
  { id: 'ai-insights', labelKey: 'aiInsights', icon: Zap },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'c1', name: 'Study', color: 'indigo' },
  { id: 'c2', name: 'Exercise', color: 'emerald' },
  { id: 'c3', name: 'Work', color: 'slate' },
  { id: 'c4', name: 'Creative', color: 'rose' }
];

export const TAG_COLORS = [
  'indigo', 'emerald', 'slate', 'rose', 'amber', 'cyan', 'violet', 'fuchsia'
];