
import { ChartColumn, LayoutDashboard, ListTodo, Zap, GitBranchPlus, BrainCircuit } from 'lucide-react';
import { Category } from './types';

export const APP_NAME = "ChronoFlow";

export const TRANSLATIONS = {
  'zh-CN': {
    aiSettings: "AI 配置",
    provider: "服务商",
    apiKey: "密钥",
    modelName: "模型",
    endpoint: "端点",
    saveConfig: "保存",
    configSaved: "已更新",
    useDefault: "默认",
    geminiDesc: "Google Gemini",
    deepseekDesc: "DeepSeek / 硅基流动",
    tasks: "专注",
    projects: "项目",
    analytics: "统计",
    aiInsights: "教练",
    aiPlanner: "规划",
    darkMode: "深色",
    lightMode: "浅色",
    export: "备份",
    import: "还原",
    langName: "繁体",
    noActiveTask: "准备好开始了吗？",
    selectTaskToStart: "输入你当下的目标，点击回车即可开始计时。",
    taskCreated: "任务已开始",
    newMilestone: "有什么新进展？",
    add: "添加",
    cancel: "取消",
    taskExplorer: "任务清单",
    standaloneTasks: "快速任务",
    all: "全部",
    active: "进行中",
    done: "已完成",
    quickAdd: "输入任务名称（例如：阅读30分钟）...",
    noTasksYet: "享受当下",
    createTaskHint: "在上方添加一个任务开始计时吧。",
    projectPlanner: "项目管理",
    projectPlannerDesc: "将任务组织成结构化的目标。",
    newProject: "新建项目",
    createProject: "创建项目",
    projectName: "项目名",
    description: "描述",
    themeColor: "主题色",
    workflowSteps: "步骤",
    addStep: "添加步骤",
    stepName: "步骤标题...",
    noDependency: "无前置",
    dependsOn: "前置:",
    workflowTip: "WBS (工作分解结构) 是将项目层级化拆解的标准。遵循米勒的『神奇数字 7±2』原则，建议将项目拆解为 3-5 个主步骤，每个步骤下细分 3-5 个任务。任务将随着前置条件的达成自动解锁。",
    totalTime: "总专注时长",
    tasksCompleted: "达成目标",
    avgTaskTime: "平均节奏",
    mostActiveTag: "主要领域",
    timeByTag: "耗时分布",
    taskDistribution: "专注偏好",
    weeklyDist: "最近一周耗时分布",
    totalDist: "总耗时分布",
    aiCoach: "AI 教练",
    aiCoachDesc: "让 AI 分析您的数据并提供建议。",
    aiPlannerTitle: "AI 目标拆解",
    aiPlannerDesc: "输入一个宏大的目标，AI 将为您构建完整的执行路径。",
    goalInputLabel: "您的核心目标",
    goalInputPlaceholder: "例如：在一个月内开发一个 React 个人博客...",
    contextInputLabel: "补充背景与细节",
    contextInputPlaceholder: "例如：我是前端初学者，每天有2小时学习时间，希望包含设计和部署环节...",
    generatePlan: "生成执行计划",
    generating: "正在拆解目标...",
    planGenerated: "计划已生成",
    analyzeWorkflow: "开始审计",
    completeTasksFirst: "请记录更多数据！",
    thinking: "AI 正在思考...",
    report: "专注审计报告",
    summary: "执行摘要",
    improvements: "行动建议",
    regenerate: "重新生成",
    waitingForParent: "锁定中",
    stepsCompleted: "个步骤已完成",
    deleteProjectWarning: "确定要删除项目结构吗？",
    deleteProject: "删除项目",
    dataTransparency: "隐私说明",
    dataSentToAI: "发送的数据",
    dataExplanation: "我们仅发送匿名的标题和时长，日志保存在本地。",
    apiKeyRequired: "已检测到 API Key。",
    listView: "列表",
    graphView: "地图",
    taskLimitReached: "仅允许同时开启一个计时任务。",
    manageCategories: "标签管理",
    categoryName: "标签名",
    newCategory: "新标签",
    selectColor: "颜色",
    deleteCategoryConfirm: "确定删除标签吗？",
    suggestedTasks: "推荐任务",
    onBreak: "休息一下",
    startBreak: "开始休息",
    endBreak: "继续工作",
    pomodoroTip: "太棒了！休息 5 分钟补充一下精力？",
    sessionProgress: "当前环节",
    startDate: "开始时间",
    endDate: "结束时间",
    schedule: "计划日程",
    frequency: "频率",
    everyDay: "每天",
    specificDays: "指定星期",
    exportProject: "导出 JSON",
    help: "使用指南",
    noProjectsYet: "暂无项目",
    createProjectHint: "创建一个项目来管理复杂的目标。",
    noProjectTasks: "项目空空如也",
    addProjectTaskHint: "添加第一个任务，开启您的项目之旅。",
    estimated: "预估",
    guide: {
      title: "欢迎使用 ChronoFlow",
      subtitle: "简单三步，找回你的专注力",
      step1Title: "1. 快速记录",
      step1Desc: "在输入框写下你想做的事，回车即可生成任务。",
      step2Title: "2. 专注计时",
      step2Desc: "点击播放按钮开始计时，进入心流状态。",
      step3Title: "3. 智能回顾",
      step3Desc: "查看统计图表，或让 AI 教练为您提供建议。",
      getStarted: "开始体验"
    },
    days: {
      Sun: "日", Mon: "一", Tue: "二", Wed: "三", Thu: "四", Fri: "五", Sat: "六"
    },
    months: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"]
  },
  'zh-TW': {
    aiSettings: "AI 設定",
    provider: "服務商",
    apiKey: "金鑰",
    modelName: "模型",
    endpoint: "端點",
    saveConfig: "儲存",
    configSaved: "已更新",
    useDefault: "預設",
    geminiDesc: "Google Gemini",
    deepseekDesc: "DeepSeek / 矽基流動",
    tasks: "專注",
    projects: "專案",
    analytics: "統計",
    aiInsights: "教練",
    aiPlanner: "規劃",
    darkMode: "深色",
    lightMode: "淺色",
    export: "備份",
    import: "還原",
    langName: "简体",
    noActiveTask: "準備好開始了嗎？",
    selectTaskToStart: "輸入你當下的目標，點擊 Enter 即可開始計時。",
    taskCreated: "任務已開始",
    newMilestone: "有什麼新進展？",
    add: "新增",
    cancel: "取消",
    taskExplorer: "任務清單",
    standaloneTasks: "快速任務",
    all: "全部",
    active: "進行中",
    done: "已完成",
    quickAdd: "輸入任務名稱（例如：閱讀30分鐘）...",
    noTasksYet: "享受當下",
    createTaskHint: "在上方新增一個任務開始計時吧。",
    projectPlanner: "專案管理",
    projectPlannerDesc: "將任務組織成結構化的目標。",
    newProject: "新建專案",
    createProject: "建立專案",
    projectName: "專案名稱",
    description: "描述",
    themeColor: "主題色",
    workflowSteps: "步驟",
    addStep: "新增步驟",
    stepName: "步驟標題...",
    noDependency: "無前置",
    dependsOn: "前置:",
    workflowTip: "WBS (工作分解結構) 是將專案層級化拆解的標準。遵循米勒的『神奇數字 7±2』原則，建議將專案拆解為 3-5 個主步驟，每個步驟下細分 3-5 個任務。任務將隨著前置條件的達成自動解鎖。",
    totalTime: "總專注時長",
    tasksCompleted: "達成目標",
    avgTaskTime: "平均節奏",
    mostActiveTag: "主要領域",
    timeByTag: "耗時分佈",
    taskDistribution: "專注偏好",
    weeklyDist: "最近一週耗時分佈",
    totalDist: "總耗時分佈",
    aiCoach: "AI 教練",
    aiCoachDesc: "讓 AI 分析您的數據並提供建議。",
    aiPlannerTitle: "AI 目標拆解",
    aiPlannerDesc: "輸入一個宏大的目標，AI 將為您構建完整的執行路徑。",
    goalInputLabel: "您的核心目標",
    goalInputPlaceholder: "例如：在一個月內開發一個 React 個人博客...",
    contextInputLabel: "補充背景與細節",
    contextInputPlaceholder: "例如：我是前端初學者，每天有2小時學習時間，希望包含設計和部署環節...",
    generatePlan: "生成執行計劃",
    generating: "正在拆解目標...",
    planGenerated: "計劃已生成",
    analyzeWorkflow: "開始審計",
    completeTasksFirst: "請記錄更多數據！",
    thinking: "AI 正在思考...",
    report: "專注審計報告",
    summary: "執行摘要",
    improvements: "行動建議",
    regenerate: "重新生成",
    waitingForParent: "鎖定中",
    stepsCompleted: "個步驟已完成",
    deleteProjectWarning: "確定要刪除專案結構嗎？",
    deleteProject: "刪除專案",
    dataTransparency: "隱私說明",
    dataSentToAI: "發送的數據",
    dataExplanation: "我們僅發送匿名的標題和時長，日誌保存在本地。",
    apiKeyRequired: "已檢測到 API Key。",
    listView: "列表",
    graphView: "地圖",
    taskLimitReached: "僅允許同時開啟一個計時任務。",
    manageCategories: "標籤管理",
    categoryName: "標籤名",
    newCategory: "新標籤",
    selectColor: "顏色",
    deleteCategoryConfirm: "確定刪除標籤嗎？",
    suggestedTasks: "推薦任務",
    onBreak: "休息一下",
    startBreak: "開始休息",
    endBreak: "繼續工作",
    pomodoroTip: "太棒了！休息 5 分鐘補充一下精力？",
    sessionProgress: "當前環節",
    startDate: "開始時間",
    endDate: "結束時間",
    schedule: "計劃日程",
    frequency: "頻率",
    everyDay: "每天",
    specificDays: "指定星期",
    exportProject: "匯出 JSON",
    help: "使用指南",
    noProjectsYet: "暫無專案",
    createProjectHint: "建立一個專案來管理複雜的目標。",
    noProjectTasks: "專案空空如也",
    addProjectTaskHint: "新增第一個任務，開啟您的專案之旅。",
    estimated: "預估",
    guide: {
      title: "歡迎使用 ChronoFlow",
      subtitle: "簡單三步，找回你的專注力",
      step1Title: "1. 快速記錄",
      step1Desc: "在輸入框寫下你想做的事，Enter 即可生成任務。",
      step2Title: "2. 專注計時",
      step2Desc: "點擊播放按鈕開始計時，進入心流狀態。",
      step3Title: "3. 智能回顧",
      step3Desc: "查看統計圖表，或讓 AI 教練為您提供建議。",
      getStarted: "開始體驗"
    },
    days: {
      Sun: "日", Mon: "一", Tue: "二", Wed: "三", Thu: "四", Fri: "五", Sat: "六"
    },
    months: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"]
  }
};

export const NAV_ITEMS = [
  { id: 'tasks', labelKey: 'tasks', icon: ListTodo },
  { id: 'ai-planner', labelKey: 'aiPlanner', icon: BrainCircuit },
  { id: 'projects', labelKey: 'projects', icon: GitBranchPlus },
  { id: 'dashboard', labelKey: 'analytics', icon: ChartColumn },
  { id: 'ai-insights', labelKey: 'aiInsights', icon: Zap },
];

export const AI_MODELS: Record<string, { name: string; models: string[]; defaultModel: string }[]> = {
  gemini: [
    { name: 'Gemini 2.5 Pro', models: ['gemini-2.5-pro-exp-03-25'], defaultModel: 'gemini-2.5-pro-exp-03-25' },
    { name: 'Gemini 2.0 Flash', models: ['gemini-2.0-flash-exp'], defaultModel: 'gemini-2.0-flash-exp' },
    { name: 'Gemini 1.5 Pro', models: ['gemini-1.5-pro', 'gemini-1.5-pro-exp'], defaultModel: 'gemini-1.5-pro' },
    { name: 'Gemini 1.5 Flash', models: ['gemini-1.5-flash', 'gemini-1.5-flash-exp'], defaultModel: 'gemini-1.5-flash' },
  ],
  deepseek: [
    { name: 'DeepSeek V3', models: ['deepseek-chat', 'deepseek-reasoner'], defaultModel: 'deepseek-chat' },
  ],
  openai: [
    { name: 'GPT-4o', models: ['gpt-4o', 'gpt-4o-turbo'], defaultModel: 'gpt-4o' },
    { name: 'GPT-4o Mini', models: ['gpt-4o-mini'], defaultModel: 'gpt-4o-mini' },
    { name: 'GPT-4 Turbo', models: ['gpt-4-turbo'], defaultModel: 'gpt-4-turbo' },
  ],
  custom: [
    { name: 'DeepSeek V3 (硅基)', models: ['deepseek-ai/DeepSeek-V3', 'deepseek-ai/DeepSeek-R1'], defaultModel: 'deepseek-ai/DeepSeek-V3' },
    { name: 'Qwen', models: ['Qwen/Qwen2.5-72B-Instruct', 'Qwen/Qwen2.5-7B-Instruct'], defaultModel: 'Qwen/Qwen2.5-72B-Instruct' },
  ],
};

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'c1', name: '学习', color: 'green' },
  { id: 'c2', name: '工作', color: 'ochre' },
  { id: 'c3', name: '计划', color: 'slate-river' },
  { id: 'c4', name: '健康', color: 'green' }
];

export const TAG_COLORS = [
  'green', 'ochre', 'slate-river', 'amber', 'cyan'
];

// Color hex values for inline styles
export const COLOR_HEX_MAP: Record<string, { main: string; light: string; lighter: string; dark: string; bg: string }> = {
  green: { main: '#84B179', light: '#A2CB8B', lighter: '#C7EABB', dark: '#507B4A', bg: '#F4F8F2' },
  ochre: { main: '#E5A952', light: '#E5D6A8', lighter: '#FAEBD6', dark: '#C27F28', bg: '#FDF6EB' },
  'slate-river': { main: '#6B8E9B', light: '#9DBABF', lighter: '#E3EBED', dark: '#415C65', bg: '#F1F5F6' },
  terracotta: { main: '#D27D67', light: '#E5B4A7', lighter: '#FBE6E1', dark: '#BC6250', bg: '#FDF2F0' },
  indigo: { main: '#6366f1', light: '#818cf8', lighter: '#c7d2fe', dark: '#4f46e5', bg: '#eef2ff' },
  amber: { main: '#f59e0b', light: '#fbbf24', lighter: '#fde68a', dark: '#d97706', bg: '#fef3c7' },
  cyan: { main: '#06b6d4', light: '#22d3ee', lighter: '#a5f3fc', dark: '#0891b2', bg: '#cffafe' },
};
